# Generated by Django 5.2.13 on 2026-04-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_revenue_account', models.CharField(default='sales_revenue', max_length=64)),
                ('accounts_receivable_account', models.CharField(default='accounts_receivable', max_length=64)),
                ('tax_liability_account', models.CharField(default='tax_liability', max_length=64)),
                ('refund_expense_account', models.CharField(default='refunds', max_length=64)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('debit_account', models.CharField(max_length=64)),
                ('credit_account', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_currency', models.CharField(default='USD', max_length=3)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('entry_type', models.CharField(choices=[('sale', 'Sale'), ('tax', 'Tax'), ('refund', 'Refund')], default='sale', max_length=16)),
                ('is_refund', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate_to_base', models.DecimalField(decimal_places=6, max_digits=14)),
                ('as_of_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='orgs.company')),
            ],
            options={
                'unique_together': {('company', 'currency', 'as_of_date')},
            },
        ),
    ]
