# Generated by Django 5.2.13 on 2026-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_path',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
