# Generated by Django 5.2.13 on 2026-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales', 'Sales'), ('inventory', 'Inventory'), ('accounting', 'Accounting'), ('hr', 'HR'), ('projects', 'Projects'), ('purchasing', 'Purchasing')], max_length=24),
        ),
    ]
